#!/usr/bin/env python3
"""
สร้างไฟล์ .xlsx ที่ import กลับเข้า cobik ได้ (ชีต Tasks + metadata)

ต้องมี openpyxl:  pip install openpyxl

ใช้ตามสัญญาใน reference/tasks-contract.md — โดยเฉพาะ:
  • ชีตต้องชื่อ "Tasks" และหัวคอลัมน์ต้องตรงเป๊ะ
  • ID ว่าง = งานใหม่ · ห้ามแต่ง ID
  • Stage ต้องเป็นชื่อที่มีอยู่แล้วในโปรเจกต์ (เฟสเดียวกัน)
  • วันที่รูปแบบ YYYY-MM-DD

เรียกใช้: แก้ list TASKS ด้านล่างแล้วรัน  python3 make_import_xlsx.py
หรือ import ฟังก์ชัน build_workbook() ไปใช้จากโค้ดอื่น
"""

from datetime import datetime, timezone
from openpyxl import Workbook

# ต้องตรงเป๊ะกับ headerKey() ในตัว parser ของแอป (lib/importXlsx.js)
HEADERS = [
    "Title", "Status", "Priority", "Phase", "Stage", "Assignees (email)",
    "Start", "Due", "Estimate (hrs)", "Actual (hrs)", "Description", "ID (ห้ามแก้)",
]

STATUS = {"todo", "in_progress", "done"}
PRIORITY = {"low", "med", "high"}
PHASE = {"pitch", "work"}


def _cell(task, key, default=""):
    v = task.get(key, default)
    return "" if v is None else v


def _assignees(task):
    a = task.get("assignees", "")
    if isinstance(a, (list, tuple)):
        return ", ".join(str(x).strip() for x in a if str(x).strip())
    return str(a or "").strip()


def build_workbook(tasks, project_id=None, exported_at=None):
    """คืน openpyxl Workbook พร้อมชีต Tasks (+ AI Guide ถ้าให้ project_id)"""
    wb = Workbook()

    # ชีต metadata (ให้แอปรู้ว่าเป็นของโปรเจกต์ไหน) — ใส่เมื่อมี project_id เท่านั้น
    if project_id:
        guide = wb.active
        guide.title = "AI Guide"
        stamp = exported_at or datetime.now(timezone.utc).isoformat()
        guide["A1"] = "AI GUIDE — generated by the cobik skill"
        guide["A2"] = f"PROJECT_ID: {project_id}"
        guide["A3"] = f"EXPORTED_AT: {stamp}"
        guide["A4"] = "FORMAT_VERSION: 1"
        ws = wb.create_sheet("Tasks")
    else:
        ws = wb.active
        ws.title = "Tasks"

    ws.append(HEADERS)  # แถวหัว = แถวที่ 1 (parser หา "Title" ในคอลัมน์ A)

    for t in tasks:
        _validate(t)
        ws.append([
            _cell(t, "title"),
            _cell(t, "status"),
            _cell(t, "priority"),
            _cell(t, "phase"),
            _cell(t, "stage"),
            _assignees(t),
            _cell(t, "start"),
            _cell(t, "due"),
            _cell(t, "estimate"),
            _cell(t, "actual"),
            _cell(t, "description"),
            _cell(t, "id"),   # เว้นว่าง = งานใหม่
        ])
    return wb


def _validate(t):
    """เตือน (raise) ค่าที่จะโดนตีกลับแน่ๆ ตั้งแต่ก่อนสร้างไฟล์"""
    if not str(t.get("title", "")).strip():
        raise ValueError(f"ทุกงานต้องมี Title: {t!r}")
    for field, allowed in (("status", STATUS), ("priority", PRIORITY), ("phase", PHASE)):
        v = str(t.get(field, "")).strip().lower()
        if v and v not in allowed:
            raise ValueError(f'{field} "{v}" ไม่ถูก — ต้องเป็นหนึ่งใน {sorted(allowed)}')
    for field in ("start", "due"):
        v = str(t.get(field, "")).strip()
        if v:
            try:
                datetime.strptime(v, "%Y-%m-%d")
            except ValueError:
                raise ValueError(f'{field} "{v}" ต้องเป็นรูปแบบ YYYY-MM-DD')


# ── แก้ตรงนี้: รายการงานที่จะเสนอ ────────────────────────────────
# ID เว้นว่าง = งานใหม่ · Stage ต้องเป็นชื่อที่มีจริงในโปรเจกต์ (เฟสเดียวกัน)
TASKS = [
    {"title": "Research คู่แข่ง", "phase": "pitch", "stage": "Research",
     "status": "todo", "priority": "med", "assignees": ["may@studio.co"],
     "start": "2026-07-14", "due": "2026-07-16", "estimate": 8},
    {"title": "ร่าง mood / direction", "phase": "pitch", "stage": "Design",
     "status": "todo", "priority": "high", "assignees": ["may@studio.co"],
     "start": "2026-07-17", "due": "2026-07-21", "estimate": 12},
    {"title": "ทำสไลด์ pitch", "phase": "pitch", "stage": "Design",
     "status": "todo", "priority": "high",
     "start": "2026-07-22", "due": "2026-07-25", "estimate": 16},
]

# ถ้ามีไฟล์ Export อยู่แล้ว ใส่ PROJECT_ID จากชีต AI Guide ของไฟล์นั้นตรงนี้
PROJECT_ID = None
OUT = "cobik-import.xlsx"

if __name__ == "__main__":
    wb = build_workbook(TASKS, project_id=PROJECT_ID)
    wb.save(OUT)
    print(f"เขียน {len(TASKS)} งานลง {OUT} — เปิดโปรเจกต์ใน cobik แล้วกด Import เพื่อตรวจในหน้า preview")
